import { Product } from "./types/Product";

export const sampleProducts: Product[] = [
  {
    name: "Nike shirt",
    slug: "nike-shirt",
    image: "../images/Nike.jpg",
    category: "shirt",
    brand: "Nike",
    price: 1000,
    countInStock: 50,
    desctiption: "Original shirt",
    numReviews: 20,
  },
  {
    name: "Jordan shirt",
    slug: "jordan-shirt",
    image: "../images/Jordan.jpg",
    category: "shirt",
    brand: "Jordan",
    price: 2000,
    countInStock: 40,
    desctiption: "Original shirt",
    numReviews: 80,
  },
  {
    name: "Lacoste shirt",
    slug: "lacoste-shirt",
    image: "../images/lacoste.jpg",
    category: "shirt",
    brand: "Lacoste",
    price: 1500,
    countInStock: 35,
    desctiption: "Original shirt",
    numReviews: 30,
  },
  {
    name: "Nike shirt",
    slug: "nike-shirt",
    image: "../images/Nike.jpg",
    category: "shirt",
    brand: "Nike",
    price: 1000,
    countInStock: 50,
    desctiption: "Original shirt",
    numReviews: 20,
  },
  {
    name: "Nike shirt",
    slug: "nike-shirt",
    image: "../images/Nike.jpg",
    category: "shirt",
    brand: "Nike",
    price: 1000,
    countInStock: 50,
    desctiption: "Original shirt",
    numReviews: 20,
  },
  {
    name: "Nike shirt",
    slug: "nike-shirt",
    image: "../images/Nike.jpg",
    category: "shirt",
    brand: "Nike",
    price: 1000,
    countInStock: 50,
    desctiption: "Original shirt",
    numReviews: 20,
  },
  {
    name: "Nike shirt",
    slug: "nike-shirt",
    image: "../images/Nike.jpg",
    category: "shirt",
    brand: "Nike",
    price: 1000,
    countInStock: 50,
    desctiption: "Original shirt",
    numReviews: 20,
  },
  {
    name: "Nike shirt",
    slug: "nike-shirt",
    image: "../images/Nike.jpg",
    category: "shirt",
    brand: "Nike",
    price: 1000,
    countInStock: 50,
    desctiption: "Original shirt",
    numReviews: 20,
  },
  {
    name: "Nike shirt",
    slug: "nike-shirt",
    image: "../images/Nike.jpg",
    category: "shirt",
    brand: "Nike",
    price: 1000,
    countInStock: 50,
    desctiption: "Original shirt",
    numReviews: 20,
  },
];
